// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vcomplete_transformer_decoder.h for the primary calling header

#ifndef VERILATED_VCOMPLETE_TRANSFORMER_DECODER___024ROOT_H_
#define VERILATED_VCOMPLETE_TRANSFORMER_DECODER___024ROOT_H_  // guard

#include "verilated.h"


class Vcomplete_transformer_decoder__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vcomplete_transformer_decoder___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(start,0,0);
        VL_OUT8(predicted_token,4,0);
        VL_OUT8(done,0,0);
        VL_OUT8(valid,0,0);
        VL_OUT8(current_state_debug,3,0);
        CData/*3:0*/ complete_transformer_decoder__DOT__current_state;
        CData/*0:0*/ complete_transformer_decoder__DOT__embed_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__pos_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attn_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__norm1_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__ffn_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__norm2_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__proj_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__argmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__embed_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__pos_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attn_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__norm1_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__ffn_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__norm2_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__proj_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__argmax_done;
        CData/*0:0*/ complete_transformer_decoder__DOT__embed_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__pos_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attn_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__norm1_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__ffn_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__norm2_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__proj_valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__argmax_valid;
        CData/*2:0*/ complete_transformer_decoder__DOT__last_pos;
        CData/*1:0*/ complete_transformer_decoder__DOT__embedding_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__embedding_inst__DOT__seq_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__embedding_inst__DOT__dim_idx;
        CData/*1:0*/ complete_transformer_decoder__DOT__embedding_inst__DOT__pipe_stage;
        CData/*1:0*/ complete_transformer_decoder__DOT__positional_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__positional_inst__DOT__seq_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__positional_inst__DOT__dim_idx;
        CData/*1:0*/ complete_transformer_decoder__DOT__positional_inst__DOT__pipe_stage;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__state;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head_start_signals;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head_done_signals;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head_valid_signals;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__seq_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__dim_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__in_dim;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__out_dim;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head0__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head0__done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head1__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head1__done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head2__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head2__done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head3__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head3__done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head4__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head4__done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head5__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head5__done;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head6__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head6__done;
    };
    struct {
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head7__valid;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head7__done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__unnamedblk2__DOT__head_id;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__unnamedblk2__DOT__local_dim;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__head_idx;
    };
    struct {
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__seq_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__seq_idx2;
        CData/*5:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__embed_idx;
        CData/*3:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__head_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__pipe_stage;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_start;
        CData/*0:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_done;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__row_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__col_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__seq_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__dim_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__pipe_stage;
        CData/*2:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__seq_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__in_dim;
        CData/*5:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__out_dim;
        CData/*7:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__hidden_dim;
        CData/*2:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__pipe_stage;
        CData/*2:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__state;
        CData/*2:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__seq_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__dim_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__pipe_stage;
        CData/*1:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__state;
        CData/*4:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__vocab_idx;
        CData/*5:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__dim_idx;
        CData/*2:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__pipe_stage;
        CData/*1:0*/ complete_transformer_decoder__DOT__argmax_inst__DOT__state;
        CData/*4:0*/ complete_transformer_decoder__DOT__argmax_inst__DOT__current_idx;
        CData/*4:0*/ complete_transformer_decoder__DOT__argmax_inst__DOT__max_index;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*10:0*/ complete_transformer_decoder__DOT__embedding_inst__DOT__embed_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__embedding_inst__DOT__embed_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__positional_inst__DOT__pos_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__wo_data;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wv_data;
    };
    struct {
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__max_val;
        SData/*8:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wq_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wq_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wk_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wv_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__enhanced_exp__Vstatic__shifted_x;
        SData/*15:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__max_val;
        SData/*15:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__gamma_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__beta_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__w1_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__w2_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__b1_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__b2_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__gamma_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__beta_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__projection_inst__DOT____Vlvbound_h188df00a__0;
        SData/*10:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__proj_addr;
        SData/*15:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__proj_data;
        SData/*15:0*/ complete_transformer_decoder__DOT__argmax_inst__DOT__max_value;
        VL_OUT(cycle_count,31,0);
        IData/*16:0*/ complete_transformer_decoder__DOT__positional_inst__DOT__temp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__proj_accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__accumulator;
    };
    struct {
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__unnamedblk2__DOT__scaled_score;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__exp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__unnamedblk2__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__mean_acc;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__var_acc;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__improved_sqrt__Vstatic__approx;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__improved_sqrt__Vstatic__new_approx;
        IData/*16:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__temp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__diff;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__diff_sq;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__with_gamma;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__final_result;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm1_inst__DOT__variance;
        IData/*31:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__accumulator;
        IData/*31:0*/ complete_transformer_decoder__DOT__ffn_inst__DOT__with_bias;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__mean_acc;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__var_acc;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__improved_sqrt__Vstatic__approx;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__improved_sqrt__Vstatic__new_approx;
        IData/*16:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__temp_sum;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__diff;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__diff_sq;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__normalized;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__with_gamma;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__final_result;
        IData/*31:0*/ complete_transformer_decoder__DOT__layer_norm2_inst__DOT__variance;
        IData/*31:0*/ complete_transformer_decoder__DOT__projection_inst__DOT__logit_accumulator;
        IData/*31:0*/ __VactIterCount;
        VL_IN8(input_sequence[8],4,0);
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__embedded_tokens;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__position_encoded;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__attention_out;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__norm1_out;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__ffn_out;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__norm2_out;
        VlUnpacked<SData/*15:0*/, 25> complete_transformer_decoder__DOT__final_logits;
        VlUnpacked<SData/*15:0*/, 16> complete_transformer_decoder__DOT____Vcellinp__projection_inst__final_hidden_state;
        VlUnpacked<SData/*15:0*/, 1600> complete_transformer_decoder__DOT__embedding_inst__DOT__embedding_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__positional_inst__DOT__pos_memory__DOT__memory;
    };
    struct {
        VlUnpacked<VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8>, 4> complete_transformer_decoder__DOT__attention_inst__DOT__head_outputs;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__concatenated;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head0__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head1__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head2__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head3__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head4__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head5__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head6__output_data;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT____Vcellout__head7__output_data;
        VlUnpacked<SData/*15:0*/, 4096> complete_transformer_decoder__DOT__attention_inst__DOT__wo_memory__DOT__memory;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head0__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head1__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head2__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head3__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head4__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__wv_mem__DOT__memory;
    };
    struct {
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head5__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head6__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__Q;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__K;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__V;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__attention_scores;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 8>, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__attention_weights;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wq_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wk_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 512> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__wv_mem__DOT__memory;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__attention_inst__DOT__head7__DOT__softmax_inst__DOT__temp_exp;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__layer_norm1_inst__DOT__sum_data;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__layer_norm1_inst__DOT__mean_val;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__layer_norm1_inst__DOT__std_val;
        VlUnpacked<SData/*15:0*/, 64> complete_transformer_decoder__DOT__layer_norm1_inst__DOT__gamma_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 64> complete_transformer_decoder__DOT__layer_norm1_inst__DOT__beta_memory__DOT__memory;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 32>, 8> complete_transformer_decoder__DOT__ffn_inst__DOT__hidden_data;
        VlUnpacked<SData/*15:0*/, 16384> complete_transformer_decoder__DOT__ffn_inst__DOT__w1_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 256> complete_transformer_decoder__DOT__ffn_inst__DOT__b1_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 16384> complete_transformer_decoder__DOT__ffn_inst__DOT__w2_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 64> complete_transformer_decoder__DOT__ffn_inst__DOT__b2_memory__DOT__memory;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 16>, 8> complete_transformer_decoder__DOT__layer_norm2_inst__DOT__sum_data;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__layer_norm2_inst__DOT__mean_val;
        VlUnpacked<SData/*15:0*/, 8> complete_transformer_decoder__DOT__layer_norm2_inst__DOT__std_val;
        VlUnpacked<SData/*15:0*/, 64> complete_transformer_decoder__DOT__layer_norm2_inst__DOT__gamma_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 64> complete_transformer_decoder__DOT__layer_norm2_inst__DOT__beta_memory__DOT__memory;
        VlUnpacked<SData/*15:0*/, 1600> complete_transformer_decoder__DOT__projection_inst__DOT__proj_memory__DOT__memory;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vcomplete_transformer_decoder__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vcomplete_transformer_decoder___024root(Vcomplete_transformer_decoder__Syms* symsp, const char* namep);
    ~Vcomplete_transformer_decoder___024root();
    VL_UNCOPYABLE(Vcomplete_transformer_decoder___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
